name: Daily Job Scraper

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run scraper
        run: python scrape.py

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main # Pull latest changes and rebase
          git add README.md visa_sponsorship_jobs_new.md # Add the modified files
          git commit -m "Update visa sponsorship jobs" || echo "No changes to commit"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


